[package]
name = "smem_exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
clap = { version = "4.5", features = ["derive"] }
prometheus = "0.13"
rayon = "1.10"
serde = { version = "1.0", features=["derive"] }
serde_yaml = "0.9"
tokio = { version = "1.37", features=["full"] }
